CUSTOM_LINK_REGEX_PATTERN = r"^[A-Za-z0-9]{1,16}$"
CUSTOM_LINK_REGEX = r"^[a-zA-Z0-9]*$"
CUSTOM_LINK_VALIDATION_MESSAGE = "Можно использовать только [A-Za-z0-9]"
CUSTOM_LINK_EXISTS_MESSAGE = "Предложенный вариант короткой ссылки уже существует."
CUSTOM_LINK_MESSAGE = "Ваш вариант короткой ссылки"
MIN_LENGHT_SHORT_LINK = 1
MAX_LENGHT_SHORT_LINK = 16
REQUIRED_FIELD_MESSAGE = "Обязательное поле"
SHORT_LINK_LENGTH = 6
SUBMIT_BUTTOM_TEXT = "Создать"
URL_REGEX_PATTERN = r"^[a-z]+://[^\/\?:]+(:[0-9]+)?(\/.*?)?(\?.*)?$"
URL_VALIDATION_MESSAGE = "Некорректный URL"
